from WData import WData
import numpy as np
import math
from scipy.linalg import block_diag
from scipy.special import bernoulli, gamma, jv

class OLS_Solver(WData):

    def __init__(self, features, xobs, tobs, type_tf, toggle_SVD, gap, p, S, mu, Mtilde, 
                 diag_reg, trunc, radius, type_rad):

        # Data inherited from Wdata
        super().__init__(features, xobs, tobs, type_tf, toggle_SVD, gap, p, S, mu, Mtilde, 
                 diag_reg, trunc)

        # Data generated by fit_OLS
        self.sum2p = self._comb_fun(2)
        self.sump = self._comb_fun(1)
        self.radius = radius
        self.radii = np.arange(2, self.M//2, 1) 
        self.type_rad = type_rad
        self.Phi = None
        self.PhiP = None
        self.centers = None        
        self.V_cell = None
        self.Vp_cell = None
        self.G0 = None
        self.b0 = None
        self.w_hat = None        


    def fit_OLS(self):

        #build Theta
        xobs_cell = [self.xobs[:,i] for i in range(self.d)]
        Theta_cell = [np.vstack([y(*xobs_cell) for y in x]).T for x in self.features]

        #compute radii
        if self.radius == None: 
            if self.type_rad == 0:
                self.radius = [self._get_r_c_hat()]
            elif self.type_rad == 1:
                rad_min = self._get_r_min()
                self.radius = np.minimum(rad_min * 2**np.arange(4), self.M//2 - 1)
        
        #build test function matrices
        if len(self.radius) == 1:
            Phi = self._get_V_L2(self.radius[0])
            PhiP = self._get_Vp_L2(self.radius[0])
            centers = self._get_centers(self.radius[0])
        else: 
            Phi = np.vstack([self._get_V_L2(rad) for rad in self.radius])
            PhiP = np.vstack([self._get_Vp_L2(rad) for rad in self.radius])
            centers = [self._get_centers(rad) for rad in self.radius]
            
        if self.toggle_SVD == True: 
            Phi, PhiP = self._svdPhi(Phi, PhiP)
        self.Phi = Phi
        self.PhiP = PhiP
        self.centers = centers        
        self.V_cell = [self.Phi]*self.d
        self.Vp_cell = [self.PhiP]*self.d        

        # build and solve linear system
        G0 = [self.Phi @ x for x, self.Phi in zip(Theta_cell, self.V_cell)]
        self.G0 = block_diag(*G0)
        self.b0 = np.hstack([-self.PhiP @ x for x, self.PhiP in zip(xobs_cell, self.Vp_cell)]).reshape(-1,1)
        self.w_hat = np.linalg.lstsq(self.G0, self.b0, rcond=None)[0].reshape(-1, 1)
        
    
    ###############################################################################################################################
    ###############################################################################################################################    


    def _get_r_c_hat(self):
        #compute derivatives at endpoints
        endpoints = self._compute_endderivative()
        
        #define freq
        freq = np.fft.fftfreq(self.Mtilde, d=1/self.Mtilde)

        #compute I for each dimension
        Is = [self._get_I(freq, endpoints[ii]) for ii in range(self.d)]
        
        normehat = []
        for radius in self.radii: 
            centers = self._get_centers(radius)
            psihat = self._get_vecpsihat_l2(freq, radius*self.dt)
            eint_hat = np.vstack([np.fft.fft(psihat*Is[ii])[centers]/np.sqrt(self.T)  for ii in range(self.d)])
            normehat.append(np.linalg.norm(eint_hat)/np.sqrt(len(centers)))
        
        normehat = np.array(normehat)
        cornerpoint = self._get_corner(np.log(normehat), self.radii, ll=2)
        return cornerpoint
    

    def _get_r_min(self):
        ntilde = int(np.floor(self.M/3))
        erms = []
        for radius in self.radii:
            Phi = self._get_V_L2(radius)   
            KK = Phi.shape[0]
            errs_temp = np.zeros((self.d,KK))
            for ii in range(self.d): #going through each dimension
                for kk in range(KK):
                    phi_u =  Phi[kk]*self.xobs[:, ii]
                    phiu_fft = (self.dt/np.sqrt(self.M*self.dt)) * np.fft.fft(phi_u)  
                    errs_temp[ii, kk] = 2. * (2. * np.pi / np.sqrt(self.M*self.dt)) * ((phiu_fft[ntilde]).imag)
            sum = np.sqrt(np.linalg.norm(errs_temp.flatten(), 2)**2/KK)
            erms.append(sum)
        erms = np.array(erms)
        rad = self._get_corner(np.log(erms), self.radii, ll=2)
        return rad

    
    ################################################################################################################################
    ################################################################################################################################
        
    
    def _get_corner(self, Ufft, xx, ll=1):
        NN = len(Ufft)
        Ufft = Ufft / max(np.abs(Ufft)) * NN
        errs = np.zeros(NN)
        for kk in range(1, NN+1):
            r1, r2 = self._build_lines(Ufft, xx, kk)
            if ll == 1:
                errs[kk-1] = np.sum(r1) + np.sum(r2) # relative l1
            elif ll == 2:
                errs[kk-1] = np.sqrt(np.sum(r1**2) + np.sum(r2**2)) # relative l2
            elif ll == 3:
                errs[kk-1] = np.sum(r1**2) + np.sum(r2**2) # relative l2
        tstarind = np.nanargmin(errs)
        return xx[tstarind] 
    

    def _build_lines(self, Ufft, xx, kk):
        NN = len(Ufft)
        subinds1 = np.arange(0, kk)
        subinds2 = np.arange(kk-1, NN)
        Ufft_av1 = Ufft[subinds1]
        Ufft_av2 = Ufft[subinds2]
        xx = np.array(xx)
        _, _, L1 = self._lin_regress(Ufft_av1, xx[subinds1])
        _, _, L2 = self._lin_regress(Ufft_av2, xx[subinds2])
        r1 = np.abs(L1/Ufft_av1-1.)
        r2 = np.abs(L2/Ufft_av2-1.)
        return r1, r2
    
    
    def _lin_regress(self, U, x):
        if x[-1] == x[0]:
            m = 0.
        else:
            m = (U[-1] - U[0]) / (x[-1] - x[0])
        b = U[0] - m * x[0]
        L = U[0] + m * (x - x[0])
        return m, b, L
    

    ################################################################################################################################
    ################################################################################################################################
    
    
    def _get_centers(self, radius):
        return np.arange(radius, self.Mp1 - radius, self.gap, dtype=int)       

    
    def _get_V_L2(self, radius):
        r = radius*self.dt
        t_r = np.linspace(-r, r, 2*radius+1)
        g = lambda t: (1 - (t/r)**2)**self.p/np.sqrt(2*r*self.sum2p)        
        phi = g(t_r)
        centers = self._get_centers(radius)
        V = np.zeros((len(centers), self.Mp1))
        for jj in range(len(centers)):
            V[jj, centers[jj]-radius:centers[jj]+radius+1] = phi*self.dt
        return V
    
    
    def _get_Vp_L2(self, radius):
        r = radius*self.dt
        t_r = np.linspace(-r, r, 2*radius+1)
        gp = lambda t: -2*t*self.p/r**2*(1 - (t/r)**2)**(self.p-1)/np.sqrt(2*r*self.sum2p)
        phip = gp(t_r)
        centers = self._get_centers(radius)
        Vp = np.zeros((len(centers), self.Mp1))
        for jj in range(len(centers)):
            Vp[jj, centers[jj]-radius:centers[jj]+radius+1] = phip*self.dt
        return Vp    
    

    def _svdPhi(self, Phi, PhiP): 
        """ 
        return orthogonal test functions
        """
        u, s, vh = np.linalg.svd(Phi)
        sv_mass = np.cumsum(s)
        if self.trunc == 0:
            r = self._get_corner(sv_mass/np.sum(s), np.arange(len(s)), ll=1) + 1
        elif self.trunc > 0: 
            r = [i for i,ss in enumerate(sv_mass) if ss/sv_mass[-1]> self.trunc][0]+1       
        ur, sr, vhr =  u[:, 0:r], s[0:r], vh[0:r]
        Phir = vhr
        P = np.diag(1/sr) @ ur.T 
        Phipr = P @ PhiP
        return Phir, Phipr
    

    ###############################################################################################################################
    ###############################################################################################################################    

    
    def _get_vecpsihat_l2(self, freq, r): 
        """
        Compute vector psihat on a set of freq 
        freq:freq
        r: radius
        """
        psihat = np.zeros(len(freq))
        for n in range(len(freq)//2+1):
            n = int(n)
            psihatn = self._get_psihatn_l2(r, n)
            psihat[n] = psihatn
            psihat[-n] = psihatn
        return psihat
    

    def _get_psihatn_l2(self, r, n): 
        """
        Compute psihat_n 
        r: radius
        n: 
        """
        if n == 0: 
            return np.sqrt(2*r/(self.sum2p*self.T))*self.sump
        else: 
            return 1/np.sqrt(2*self.sum2p)/r**self.p*(self.T/(n*np.pi))**self.p/np.sqrt(n)*gamma(self.p+1)*jv(self.p+1/2, 2*np.pi*n*r/self.T)
    

    ####################################################################################################################################################
    ####################################################################################################################################################
    
    
    def _get_I(self, freq, endpoints): 
        I = np.zeros(len(freq), dtype=np.complex128)
        for n in freq: 
            n = int(n)
            I[n] = self._get_In(n, endpoints)   
        return I
    
    
    def _get_In(self, n, endpoints):
        sumS = 0
        for s in range(1, self.S+1):
            sumS += self._es(s, n, endpoints)
        return endpoints[0] + sumS #- dt/2*(2*np.pi*n*1j/T*endpoints[0] + endpoints[1]) 
    

    def _es(self, s, n, endpoints):
        suml = 0
        for ll in range(2*s+1):
            suml += math.comb(2*s, ll)*(2*np.pi*n*1j/self.T)**(2*s-ll)*endpoints[ll]
        suml *= bernoulli(2*s)[-1]/math.factorial(2*s)*self.dt**(2*s)
        return suml
    
    
    ################################################################################################################################
    ################################################################################################################################    
    
    
    def _compute_endderivative(self):
        endpoints = []
        for ii in range(self.d):
            if self.S == 0: 
                epts_i = [self._getFD_endpoints(ll, self.mu[ll], self.xobs[:, ii]) for ll in range(2)]
            else:
                epts_i = [self._getFD_endpoints(ll, self.mu[ll], self.xobs[:, ii]) for ll in range(2*self.S+1)]
            endpoints.append(epts_i)
        return endpoints
    

    def _getFD_endpoints(self, l, mu, f):
        """Compute endpts FD approx of l-th derivative with order mu accurate
        l: derivative order, l = 0, 1, ...
        mu: order of accuracy mu = 1, 2, 3... 
        f data: 1D array
        """
        if l == 0: 
            D0 = f[0]
            DT = f[-1]
        else: 
            #get forward different weights
            A = np.zeros((mu + l, mu + l))
            b = np.zeros(mu + l)
            for i in range(mu + l):
                for m in range(mu + l):
                    A[i, m] = m**i
                    if i == l:
                        b[i] = math.factorial(l)
            #weightsFD: forward difference, weightsBD: backward difference 
            weightsFD = np.linalg.solve(A, b)
            if l % 2 == 0: 
                weightsBD = weightsFD.copy()
            else: 
                weightsBD = -weightsFD.copy()[::-1]
            D0 = weightsFD.dot(f[0: mu + l])/self.dt**l
            DT = weightsBD.dot(f[-(mu+l):])/self.dt**l
        return DT - D0
    

################################################################################################################################
################################################################################################################################
    